# PostgreSQL. Versions 8.2 and up are supported.
# Use 'createuser -s postgres' to create a general purpose db (super)user.

development: &default
  adapter: postgis
  encoding: unicode
  database: velocitas_core_development
  username: postgres
  pool: 5
  timeout: 5000

test:
  <<: *default
  adapter: postgis
  database: velocitas_core_test
  min_messages: warning

acceptance:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: velocitas_core_production
  url: <%= ENV['DATABASE_URL'] %>
